---
- name: install docker
  yum:
    name='docker'
    state=latest

- name: service docker
  service:
    name=docker
    state=started
    enabled=yes


- name: Install pip
  package:
    name: python3-pip
    state: present
    update_cache: true

- name: installing docker SDK
  command: "pip3 install docker"
# - name: Install Docker SDK for Python
#   pip:
#     name: "docker" 
#     become: yes
#     executable: pip3

- name: pulling docker image
  docker_image:
    name: nginx
    source: pull

- name: Add user to docker group [sudo usermod -a -G docker ec2-user]
  user:
    name: "{{ansible_user}}"
    group: docker

- name: Download docker-compose {{ docker_compose_version }}
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: ~/docker-compose
    mode: '+x'

- name: Check docker-compose exists
  stat: path=~/docker-compose
  register: docker_compose

- name: Move docker-compose to /usr/local/bin/docker-compose
  command: mv ~/docker-compose /usr/local/bin/docker-compose
  when: docker_compose.stat.exists


# - name: Pull default Docker image
#   docker_image:
#     name: "{{ default_container_image }}"
#     source: pull




# - name: Install Nginx
#   docker_container:
#     name: nginx
#     image: nginx
#     detach: True
#     ports:
#       - "8080:80"
#     expose:
#       - "8080"
#     # volumes:
#       # - /etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro